#%RAML 1.0

title: E-Commerce API
baseUri: http://api.goodwill.co.ke/
version: v1

/products:
    get:
    /{productId}:
        get: 

/users:
    post:
    get:
    /{userName}:
        get:
        put: 

/carts:
    post:
    get:
    /{cartId}: 
        get:
        put:
